# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - flow-community

patreon: # Replace with a single Patreon username
  - flow-community

open_collective: # Replace with a single Open Collective username
  - flow-community

ko_fi: # Replace with a single Ko-fi username
  - flow-community

tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
  -

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://paypal.me/flowcommunity
